### ISSUE TITLE
trying to use the layer from other aws region

### ISSUE THREAD

**Issue by bein87** [shelfio/libreoffice-lambda-layer#1]
when trying to add a layer on AWS Lambdam eu-west region, i get error "You are not authorized to perform: lambda:GetLayerVersion.".  it seems to be a regions issues and not roles/permissions. can you please deploy this to all regions?

thanks

**Comment by AlexBa** [comment]
Hello, I got exactly the same problem: "You are not authorized to perform: lambda:GetLayerVersion.". Would it be possible to deploy the package into all the different regions or do we have to deploy our Lambda functions to us-east-1?

**Comment by vladgolubev** [comment]
Hey guys,

you're right, right now it's being published only to the `us-east-1` as stated here: https://github.com/shelfio/libreoffice-lambda-layer/blob/master/publish.sh#L7

I didn't know will be there a demand for other regions, so I left only 1 initially.

Now I see there is a demand, so I'll make the necessary changes to publish it to all the regions tomorrow and let you know!

**Comment by AlexBa** [comment]
Thank you very much!

**Comment by vladgolubev** [comment]
Turns out it's not so easy to deploy layer to all the regions. I need to create S3 bucket to host layer's `.zip` in each region... Here is the explanation: https://stackoverflow.com/a/48326181/2727317

How difficult would it be for you to deploy Lambda to the `us-east-1`?

Anyway, could you please list your preferable 1-2 regions so maybe I could create the necessary S3 buckets and attempt a cross-region deployment

**Comment by bein87** [comment]
First of all, thanks for the quick response!
It will be great if you could deploy to eu-west-1. deploying the lambda to us-east-1 will be very difficult on my side, as all of our account is in eu and it will create other issues to handle

**Comment by bein87** [comment]
can i create a layer on my own? so my code will not be affected if you will change something.. planning to use it for production product

**Comment by vladgolubev** [comment]
@bein87 if you use a specific version of the layer it will never change or disappear even if I change code. But sure, you can create a layer on your own, just download `layer.zip` and publish it in your account just as in the `publish.sh` script

**Comment by vladgolubev** [comment]
@bein87 here you are, I've just published the layer in the `eu-west-1` region:

```
arn:aws:lambda:eu-west-1:764866452798:layer:libreoffice:1
```

**Comment by bein87** [comment]
@vladgolubev  wow thanks!
I was able to add this layer to my lambda :) THANKS! (tried to download to zip as well, but when uploading it via aws console, it allows files with max size of 50MB.)

Now i have another quick question..  im trying to use it with aws-lambda-libreoffice, (from the readme-"Works well with aws-lambda-libreoffice npm package"), but after adding the layer, i see no change. i still get "Error: ENOENT: no such file or directory, open '/opt/lo.tar.br' {}"

Am I missing something?
(I tried to change the input directory to "/tmp/", but got " Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }")


code:
const {convertTo, canBeConvertedToPDF} = require('@shelf/aws-lambda-libreoffice');
fs.readFile(filename, (err, data) => {
    convertTo(data, 'pdf').catch(err =>console.log(err));
}

**Comment by vladgolubev** [comment]
@bein87 looks like you're using the old version of `aws-lambda-libreoffice` package which expects a brotli archive. What version of the library are you using?

**Comment by bein87** [comment]
"@shelf/aws-lambda-libreoffice": "^2.2.0"

**Comment by vladgolubev** [comment]
@bein87 hmm, strange, it works well in my Lambda for quite some time...

Looks like the layer was not properly attached? Do you use Node 8.10 or 10.x runtime?

**Comment by bein87** [comment]
I attached it according to the manual. just clicked on "add a layer", changed to ARN, pasted the link, and saved changes. maybe I need to republish or something similar? 
![image](https://user-images.githubusercontent.com/9053169/59768279-c6de5300-92ac-11e9-938c-909bceba1b1e.png)

**Comment by vladgolubev** [comment]
@bein87 maybe you can share a code snippet or smth, otherwise I have no idea where the problem is :(

**Comment by bein87** [comment]
We use Node 8.10.
this is a very simple code - [getting file from S3 as buffer, and sending it to conversion]
`
const {convertTo, canBeConvertedToPDF} = require('@shelf/aws-lambda-libreoffice');
const image = S3.getObject({
        Bucket: srcBucket,
        Key: srcKey
    }, (err, data) => {
        if (err) {
            console.log("Can't get file");
            console.log(err);
            return;
        } else {
                    var name = data.ETag.substring(data.ETag.indexOf("\"")+1,data.ETag.lastIndexOf("\""));
                    var filename = "/tmp/"+ name +"."+ fileType;
                    fs.writeFile(filename, data.Body, "utf-8",() => {
                         fs.readFile(filename, (err, data) => {
                            if (err){
                                console.log("error with reading file name. err:" + err);
                            }
 
 
                            var aafasdf = convertTo(data, 'pdf').catch(err =>
                            console.log(err)
                            );
                     });
              });
       }
}`

**Comment by vladgolubev** [comment]
@bein87 `convertTo` accepts a filename in the `/tmp` folder, so the code should be smth like this

```js
const { convertTo, canBeConvertedToPDF } = require("@shelf/aws-lambda-libreoffice");
const image = S3.getObject(
  {
    Bucket: srcBucket,
    Key: srcKey
  },
  (err, { Body, Etag }) => {
    if (err) {
      console.log("Can't get file");
      console.log(err);
      return;
    } else {
      var name = ETag.substring(ETag.indexOf('"') + 1, ETag.lastIndexOf('"'));
      var filename = "/tmp/" + name + "." + fileType;

      fs.writeFile(filename, Body, "utf-8", () => {
        convertTo(name + "." + fileType, "pdf")
          .then(() => console.log("file is converted"))
          .catch(err => console.log(err));
      });
    }
  }
);
```

**Comment by bein87** [comment]
same error :\
did you try to run the code? 

{ Error: ENOENT: no such file or directory, open '/opt/lo.tar.br'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/lo.tar.br' }

**Comment by bein87** [comment]
seems that it still tries to take the file from '/opt/lo.tar.br'(which does not exist) and not from '/tmp/'.
you said that it does not suppose to do so in this version. 
can you please check why? and how to change it?  maybe if ill change the path it will work?

**Comment by vladgolubev** [comment]
@bein87 I was wrong, the new version expects `/opt/lo.tar.br` brotli archive, I confused it with https://github.com/shelfio/aws-lambda-tesseract which was also updated recently...

`lo.tar.br` must be in the `opt` and it's automatically put there by AWS if you attach the layer. It's being unpacked to `/tmp` later during runtime

Can you please add this line to the Lambda and paste the output?

```
const {execFileSync} = require('child_process');

console.log(execFileSync(`ls -alh /opt`).toString('utf8'));
```

**Comment by bein87** [comment]
Function Logs
2019-06-19 16:31:56.419 Error: spawnSync ls -alh /opt ENOENT
    at _errnoException (util.js:1022:11)
    at spawnSync (child_process.js:579:20)
    at execFileSync (child_process.js:616:13)
    at exports.handler (/var/task/testResizeV2/index.js:30:13)



im attaching the directories:
![image](https://user-images.githubusercontent.com/9053169/59783427-cb186980-92c8-11e9-9cd9-29596ff48478.png)

BTW, i uploaded the layer.ZIP to my S3 and than created a layer on my account (and not with the ARN). I thought maybe it will do any change... and, well, it didnt. 
according to what you said, the layer creation did not applied succecssfuly, as 'lo.tar.br' was not created?

**Comment by AlexBa** [comment]
Would it be possible to deploy the Lambda Layer to eu-central-1? Or is it possible to use the Lambda layer from eu-west-1?

**Comment by vladgolubev** [comment]
Looks like you don't even have the  `/opt` directory

Are you sure you are running this in the **AWS Lambda Node 8.10** runtime?

I've just created an empty Lambda function without any layers and this is the expected output:

```
total 8.0K
drwxr-xr-x  2 root root 4.0K Apr  9 19:57 .
dr-xr-xr-x 17 root root 4.0K Apr 17 09:08 ..
```

**Comment by AlexBa** [comment]
One question: Would it be possible to deploy the Lambda layer to eu-central-1 too? That would be very helpful since my S3 buckets with all the event listeners (must be same region) are located in eu-central-1.

**Comment by vladgolubev** [comment]
@AlexBa here you are `arn:aws:lambda:eu-central-1:764866452798:layer:libreoffice:1`

**Comment by bein87** [comment]
just for future common knowladge - I run my code with AWS cloud9 IED. apperently, it 'ignores' aws layers. when deploying to the server, it seems to be ok.

**Comment by aaronsturm** [comment]
I could also use it in us-west-2 if you're willing to upload it there as well? Thanks!

**Comment by vladgolubev** [comment]
Hey @aaronsturm 

sure, here you are 🙌 

```
arn:aws:lambda:us-west-2:764866452798:layer:libreoffice:1
```

**Comment by aaronsturm** [comment]
Wow, you rock, thanks for the quick response!!

**Comment by kurtaschliman** [comment]
@vladgolubev Any chance you add us-east-2? Thank you!

**Comment by vladgolubev** [comment]
@kurtaschliman 

sure

```
arn:aws:lambda:us-east-2:764866452798:layer:libreoffice:1
```

**Comment by kurtaschliman** [comment]
Awesome. Thanks @vladgolubev!

**Comment by miftahjaf** [comment]
Hi @vladgolubev , is it possible for you to add it to ap-south-1 please.

**Comment by mingcow** [comment]
hi, any chance you can add ap-southeast-1, please :)))

**Comment by vladgolubev** [comment]
@mingcow new regions:

* `arn:aws:lambda:eu-west-2:764866452798:layer:libreoffice:1`
* `arn:aws:lambda:ap-southeast-1:764866452798:layer:libreoffice:1`

**Comment by vladgolubev** [comment]
@miftahjaf here you are:

* `arn:aws:lambda:ap-south-1:764866452798:layer:libreoffice:1`

**Comment by BradleyDHobbs** [comment]
Is it possible to add ca-central-1? 

Thanks!

**Comment by vladgolubev** [comment]
@BradleyDHobbs sure! here you are:

* `arn:aws:lambda:ca-central-1:764866452798:layer:libreoffice:1`

**Comment by luiz-mai** [comment]
Hi, @vladgolubev.
Any chances to upload the layer to the sa-east region?

(Btw, congratz on the great lib)

**Comment by lcyin** [comment]
Thanks for the great library.

Is it possible to add ap-east-1 too?

**Comment by maurice-ellis** [comment]
And us-west-1? Surprised that people use 2 before 1

**Comment by sih99** [comment]
Hi, @vladgolubev.
Is it possible to add **ap-northeast-2** ?

Thanks!

**Comment by vladgolubev** [comment]
@sih99 PRs are welcome. You can create a PR that publishes to that region
