### ISSUE TITLE
Ability to connfigure PDF version

### ISSUE THREAD

**Issue by pavinthan** [shelfio/libreoffice-lambda-layer#12]
so able to convert to PDF/A

**Comment by pavinthan** [comment]
I'm closing this issue because I have fixed by creating new registrymodifications.xcu file with SelectPdfVersion property in my project root dir and copy that file to execution root `/tmp/instdir/user/registrymodifications.xcu` then use `--convert-to pdf:writer_pdf_Export` command

Thanks for your work 👍

**Comment by vladgolubev** [comment]
Thanks for sharing a solution, @pavinthan!
