### ISSUE TITLE
Error Cloning Repo (git lfs)

### ISSUE THREAD

**Issue by dehli** [shelfio/libreoffice-lambda-layer#14]
Hi, I'd like to clone this repo and view the layer however I'm getting the following error:

```
Error downloading object: layer.zip (e3c2ba4): Smudge error: Error downloading layer.zip (e3c2ba496511cdd8adc3ebffe6207385f51a8f0052e6f7dcd1e2cf25935b6c90): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Any ideas?

Thanks!

**Comment by dehli** [comment]
As a workaround I used the following command to view the layer content. This isn't really an issue for me anymore but feel free to reopen if you'd like!

```
aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-east-1:764866452798:layer:libreoffice:8
```

**Comment by vladgolubev** [comment]
Glad you've found out this workaround 😅 

Otherwise, you can check out the [CI configuration](https://github.com/shelfio/libreoffice-lambda-layer/blob/master/.circleci/config.yml#L12) to see how it installs git lfs
