### ISSUE TITLE
Doesn't work with nodejs10.x/nodejs12.x

### ISSUE THREAD

**Issue by RimashMohomed** [shelfio/libreoffice-lambda-layer#16]
Trying to deploy with nodejs10.x, which result in a error.

`"Error: The module '/opt/node_modules/@shelf/aws-lambda-brotli-unpacker/src/iltorb/build/bindings/iltorb.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 57. This version of Node.js requires\nNODE_MODULE_VERSION 64. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",`

As the error suggest layer is built in NODE MODULE VERSION 57 but the nodejs10.x requires to be built in NODE MODULE VERSION >= 64

Can i have a build in NODE MODULE VERSION >= 64 ?

**Comment by vladgolubev** [comment]
Hey @RimashMohomed 

This is due to Node.js 10 environment runs on Amazon Linux 2, while this layer was compiled for Amazon Linux 1. We're working on making it work with newer environments at the moment. I'll let you know once it works with Node.js 10 or 12

**Comment by RimashMohomed** [comment]
@vladgolubev Thanks for the update.

We are expecting to use this layer in production environment, do you find any reason not to ? and Is there any  ETL for the Amazon Linux 2 build?

**Comment by vladgolubev** [comment]
@RimashMohomed Amazon Linux 2 build is due to this week thanks to @maaraanas! 

You should be fine using it in production. The only risk is a vulnerability in the LibreOffice itself. But this can be mitigated by granting minimum required privileges to your Lambda.

**Comment by RimashMohomed** [comment]
@vladgolubev thank you for the quick response, will close the issue after testing !! 

@maaraanas thank you for the contribution

**Comment by RimashMohomed** [comment]
@vladgolubev Is this done? where i can find the ARN and If i am to use with https://github.com/shelfio/aws-lambda-libreoffice how to do ?

**Comment by andymccullough** [comment]
also interested in hearing about the progress of this - i'd love to be able to use it for node 12, thanks!

**Comment by vladgolubev** [comment]
Good news: I was able to compile & run LibreOffice in the Node.js 12.x environment.
Bad news: it's size is ~400 MB

**Comment by RimashMohomed** [comment]
@vladgolubev Any chance ?

**Comment by tadasauciunas** [comment]
Do I understand correctly that it's currently impossible to use the layer successfully with any version of node in aws ? Are there no temporary workarounds?

**Comment by vladgolubev** [comment]
Hey @tadasauciunas and other folks

We've just published a new version that works with nodejs10.x/nodejs12.x 🎉 

https://github.com/shelfio/libreoffice-lambda-layer#version-arns

**Comment by tadasauciunas** [comment]
Thank you !

**Comment by RimashMohomed** [comment]
@vladgolubev thanks a lot, does the npm package is released as well?

**Comment by tadasauciunas** [comment]
@RimashMohomed Did you update the layer on which you depend after upgrading to the 3.0.0 package version ? See updated layer ARNs in the readme file of this repository

**Comment by RimashMohomed** [comment]
@tadasauciunas yes it solved the particular issue, but now layer sized exceeds max limit (250mb), as i using two more layers.
