### ISSUE TITLE
what does this layer do?

### ISSUE THREAD

**Issue by d3netxer** [shelfio/libreoffice-lambda-layer#18]
Can you please explain what this layer does? Thanks

**Comment by d3netxer** [comment]
oh, I think the layer consists of these files probably: https://github.com/vladgolubev/serverless-libreoffice/tree/master/src

**Comment by vladgolubev** [comment]
Hey @d3netxer 

This layer consists of this file: https://github.com/vladgolubev/serverless-libreoffice/releases/tag/v6.1.0.0.alpha0

![image](https://user-images.githubusercontent.com/3817380/71246936-61812280-2320-11ea-93de-81abe012fb6b.png)

You can download https://github.com/shelfio/libreoffice-lambda-layer/blob/master/layer.zip and check it yourself
