### ISSUE TITLE
Path to soffice binary

### ISSUE THREAD

**Issue by ivanovv** [shelfio/libreoffice-lambda-layer#3]
The README says:
> You can add this layer to any Lambda function you want – no matter what runtime

I would love to use the binary from this layer, but all I see in `/opt` is `lo.tar.br`. Do I have to extract the archive or is there a way to get the binary?

**Comment by vladgolubev** [comment]
Hey @ivanovv, 

yes, you have to extract binary from the archive, since it's too big to fit into 250 MB Lambda artifact limit. 

If there is no brotli binary for your runtime, you can repack LO with plain zip by sacrificing artifact size and unpacking performance.

**Comment by ncruces** [comment]
I was using this in Google Cloud, don't know if you remember?
For us Google users, is there a way to download the lo.tar.br?
Sorry to hijack this!

**Comment by vladgolubev** [comment]
@ncruces you can download `layer.zip` from this repo, unpack and put `lo.tar.br` to Google Cloud Storage

**Comment by ivanovv** [comment]
@vladgolubev thanks, I ran into an issue of free space several times until I finally figured out that I had to use pipe to do everything on the fly.

Here is a command for anyone who might need it in future:

```bash
cd /tmp && /var/task/brotli -d /opt/lo.tar.br -c | tar xvf -
```
The LibreOffice binary will be avail here: `/tmp/instdir/program/soffice`
