### ISSUE TITLE
How to unpack lo.tar.br using brotli?

### ISSUE THREAD

**Issue by Jun711** [shelfio/libreoffice-lambda-layer#43]
Hi, I tried to use Nodejs brotli to unpack the lo.tar.br file but I am not sure how to use it. After `zlib.brotliDecompress`, the tar.br file is still not unpacked.  
Could you please provide an example? Thank you

What I tried
```
const libreOfficePacked = fs.readFileSync('/tmp/lo.tar.br')
zlib.brotliDecompress(libreOfficePacked)
```

https://nodejs.org/api/zlib.html#zlibbrotlidecompressbuffer-options-callback
```
zlib.brotliDecompress(buffer[, options], callback)
```

From [brotli npm doc](https://www.npmjs.com/package/brotli), 
```
// decode a buffer where the output size is known
brotli.decompress(compressedData, uncompressedLength);
 
// decode a buffer where the output size is not known
brotli.decompress(fs.readFileSync('compressed.bin'));
```

**Comment by vladgolubev** [comment]
Here is the example: https://github.com/shelfio/aws-lambda-libreoffice/blob/master/src/unpack.ts
