### ISSUE TITLE
eu-west-3 not supported

### ISSUE THREAD

**Issue by Neonexus45** [shelfio/libreoffice-lambda-layer#48]
Hey, could it be possible to update this layer to the region eu-west-3 ? I'm not finding any alternative to this layer and I can't change the region since I do not own the aws account

**Comment by vladgolubev** [comment]
Done
https://app.circleci.com/pipelines/github/shelfio/libreoffice-lambda-layer/107/workflows/8b7c128e-3720-4e08-be8e-ba3db3ef4546/jobs/302

```
arn:aws:lambda:eu-west-3:764866452798:layer:libreoffice-brotli:1
arn:aws:lambda:eu-west-3:764866452798:layer:libreoffice-gzip:1
```
